### ISSUE TITLE
Enable Wayland socket

### ISSUE THREAD

**Issue by p1u3o** [flathub/com.leinardi.gst#3]
Hey, great app :)

I noticed GST runs with Xwayland, but after running it manually with --socket=wayland I don't see any issues.

Unless there's any issue I'm not aware of, could the wayland socket be enabled?

**Comment by leinardi** [comment]
Hey sure, I can't test Wayland myself but, since you tested it, I'll enable it :+1:

**Comment by p1u3o** [comment]
Awesome!

You can also change
`--socket=x11` to `--socket=fallback-x11` which will disable the Xwayland socket when running under Wayland.
