### ISSUE TITLE
monitor hardware temperatures do not appear?

### ISSUE THREAD

**Issue by FastOSlinux** [flathub/com.leinardi.gst#4]
Monitor hardware does not show temperatures like sensors on terminal, bug?

![Captura de tela de 2020-01-28 12-43-50](https://user-images.githubusercontent.com/17401812/73279591-25b56480-41cc-11ea-9b8f-90f401b2338b.png)

**Comment by leinardi** [comment]
Please use the official issue tracker to report GST bugs: https://gitlab.com/leinardi/gst/issues

This repository it's only used for the publication on Flathub.

PS
From the screenshot it seems you just have to scroll to the right to see the temperatures.
